### ISSUE TITLE
BOM

### ISSUE THREAD

**Issue by iCityWork** [UpLateGeek/Let-s-Make-Some-Memories#1]
Hi, this looks cool, do you have a BOM for it?
Thanks!

**Comment by NukemD** [comment]
According to the Vogons thread, you'll need two 4M x 4-bit SOJ-20 DRAM chips, which go in places IC1 and IC2. If you want to turn it into a parity module, you'll need a further 4M x 1-bit SOJ-20DRAM chip to go in position IC3.

A candidate for the 4M x 4-bit is a TC5117400CSJ-60, or any equivalent.
A candidate for the 4M x 1-bit is a HYB514100BJ-60, or any equivalent. These are only needed if you want a parity module.

You'll also need two or three 100 nF SMD ceramic capacitors, one next to each memory chip for decoupling. I'm not sure of the size.

You can sacrifice 72 pin SIMMs for their memory chips, but you'll want to verify the pinout of the memory chips. You'll also want to avoid using EDO and only use FPM memory for compatibility reasons. I don't know if there ever was an EDO 30 pin SIMM, and many memory controllers from that era expect PM or FPM DRAM only.

**Comment by UpLateGeek** [comment]
Thanks for the suggestion, NukemD and another contributor have added [BOM.md](https://github.com/UpLateGeek/Let-s-Make-Some-Memories/blob/master/BOM.md), which I've updated with some alternate part numbers. Please let me know if there's anything else needed for this, or if you're happy for me to close this issue?

**Comment by NukemD** [comment]
You could probably drop the timing suffix on the RAM to allow a wider variety of memory chips. Memory manufacturers often had several speed ratings of the same part number.

60ns was blazing fast for a 30 pin simm and really only available towards the end of the memory type. Many computers of the era worked fine with slower memory, but once you got past 80ns, memory chips were generally in a different package type like QFP instead of SOJ-20, and had a much lower density that required more chips.

**Comment by iCityWork** [comment]
Thank you! This is great, thinking about building some and offering them on
my website for people who don't want to build their own.
www.vintagecomputercenter.com


*/Gavin/*


*Gavin Haubelt*

Founder/Lead Developer

iCityWork

(559) 492-6318

gavin.haubelt@icitywork.com <gavin@icitywork.com>

www.iCityWork.com <http://www.icitywork.com/>

@iCityWork <https://twitter.com/iCityWork>

FaceBook /icitywork <https://www.facebook.com/icitywork>

ᐧ

**Comment by UpLateGeek** [comment]
I've removed the timing suffix from the part numbers.

Unfortunately the gerbers were produced using the free maker license for Eagle, which stipulates that any projects created and released under the license must be open source and non-commercial. Hence why the [LICENSE.md](https://github.com/UpLateGeek/Let-s-Make-Some-Memories/blob/master/LICENSE.md) is CC-A-NC-SA. I originally planned on porting the project to Kicad, but I haven't gotten around to it since I also have to learn how to use it.

**Comment by NukemD** [comment]
If you do eventually get time to work on this project again, could you make a 1 MB version? There are quite a few machines which won't accept more than 1 MB 30 pin SIMMs.

**Comment by levkar** [comment]
+1 for 1MB

**Comment by pfuentes69** [comment]
Thanks for this project.
I tried to locate the memory ICs but I haven't been lucky.
Is it possible to know any on-line source to purchase?

**Comment by NukemD** [comment]
> Thanks for this project. I tried to locate the memory ICs but I haven't been lucky. Is it possible to know any on-line source to purchase?

UTSource, Alibaba or Aliexpress. You can plug in the generic part number for 4mbit x 4 chips, which is "5117400" and the 4mbit x 1 (if you want a parity module) is "514100". You'll need SOJ-24 package chips for this project.

Some examples:
https://www.utsource.net/sch/5117400.html
https://www.utsource.net/sch/514100.html

**Comment by pfuentes69** [comment]
> > Thanks for this project. I tried to locate the memory ICs but I haven't been lucky. Is it possible to know any on-line source to purchase?
> 
> UTSource, Alibaba or Aliexpress. You can plug in the generic part number for 4mbit x 4 chips, which is "5117400" and the 4mbit x 1 (if you want a parity module) is "514100". You'll need SOJ-24 package chips for this project.
> 
> Some examples: https://www.utsource.net/sch/5117400.html https://www.utsource.net/sch/514100.html

Thanks!
It doesn't show up in Aliexpress, but this helps a lot!

**Comment by UpLateGeek** [comment]
Thanks for the reply, NukemD. And good luck with your modules, Pedro!

I just noticed I forgot to close this issue, so I'll go ahead and do that now.

**Comment by pfuentes69** [comment]
Hi there. I need to come back on this...
I didn't find the chips but then I found some 16MB 72-pin modules that were (apparently) using the same chips. In particular, these modules had the TM5117400HJ-6, so I got a couple and desoldered the chips with hot air.

Now I tried to put these chips in the PCB and I just see they don't fit. The placeholder in the PCB is made for chips with 12 pins on each side, like these chips I got, but the PCB has a single empty space between each group of 6 pins, while the chips I got have a double empty space.

I'm not expert at all on SMD packages, so... What did I miss here?

**Comment by pfuentes69** [comment]
![image](https://user-images.githubusercontent.com/34808198/145709537-1ccf8acf-0e5d-4a14-bc00-176e6ec34e1b.jpeg)

This is the issue I have.

**Comment by NukemD** [comment]
Well, that is a SOJ-24 chip, but the package looks fatter and longer than what I'd normally expect. I checked a few of my 72 pin SIMMs with 5117400 modules on them and none of them look to be like the one in the picture. Yours sort of looks like a SOJ-28 package where four pins were removed.

UTSource has some chips that look like they're correct. The pitch between the two groups of six is much closer and more closely matches with the pads on the PCB.

https://www.utsource.net/itm/p/11243368.html

**Comment by UpLateGeek** [comment]
I haven't been able to find a datasheet for your specific part, but it appears to be a clone of the Toshiba TC5117400J, which is a 400mil wide SOJ 28/24. Confusingly there's also a TC5117400BSJ/CSJ, which is a 300mil wide SOJ 26/24 that is compatible with the design of these boards.

Page 149 (labelled A-139) of the attached PDF shows the datasheet for the Toshiba version of your part, so it's definitely different.

Unfortunately to make these chips work would require a complete re-design of the board, which probably isn't worth the effort. The only thing I could suggest would be to source some compatible chips and use these to practice soldering them onto the modules you took them off.

[1994_Toshiba_DRAM_Components_and_Modules.pdf](https://github.com/UpLateGeek/Let-s-Make-Some-Memories/files/7700054/1994_Toshiba_DRAM_Components_and_Modules.pdf)

**Comment by pfuentes69** [comment]
Thanks. I found a 32MB SIMM that seems to use ICs with the right package, so I'll remove the chips from it. Let's see if I'm more lucky now. 
(I'm in Europe, and the shipping cost from UTSource is too high, unfortunately)

**Comment by Realloy** [comment]
The footprint look wrong also..

Den sön 12 dec. 2021 11:55Pedro F ***@***.***> skrev:

**Comment by pfuentes69** [comment]
I received the "new" SIMM and the ICs seem adequate. So the lesson I learned is that 5117400 can be found in different packages 

![image](https://user-images.githubusercontent.com/34808198/146354241-46a48090-a95e-48c8-9bac-ca940ce0cab2.jpeg)
